import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className='heading'>Hunting Coders</h1>
          <div>
            <img src="/coders.avif" 
                width={270}
                height={159}
                alt="coders image" />
          </div>

          <h3>Popualar Blogs</h3>
          <article>
            <h5>This is blog header</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, vitae saepe. Eos, voluptatum delectus, explicabo nam maxime quas
            </p>
          </article>
          <article>
            <h5>This is blog header</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, vitae saepe. Eos, voluptatum delectus, explicabo nam maxime quas
            </p>
          </article>
          <article>
            <h5>This is blog header</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, vitae saepe. Eos, voluptatum delectus, explicabo nam maxime
            </p>
          </article>
          <article>
            <h5>This is blog header</h5>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, vitae saepe. Eos, voluptatum delectus, explicabo nam maxime quas
            </p>
          </article>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
